### PR TITLE
fix: await player to be destroyed before re-creating it

### LINKED ISSUE #355: Youtube component disappearing immediately after page loads
Youtube component is very cool, but disappearing immediately after page loads. Tested with example from here https://github.com/tjallingt/react-youtube . What can be the reason?

### PR DESCRIPTION
**Pull request by victoragnez**
To make it compatible with Strict Mode of React 18

Closes #355

### CODE REVIEW

File: packages/react-youtube/src/YouTube.tsx [hunk 1]
```diff
@@ -300,37 +306,60 @@ class YouTube extends React.Component<YouTubeProps> {
...
-    if (typeof document === 'undefined') return;
-    // create player
-    const playerOpts: Options = {
-      ...this.props.opts,
-      // preload the `videoId` video if one is already given
-      videoId: this.props.videoId,
+    const doCreatePlayer = () => {
+      // do not attempt to create a player server-side, it won't work
+      if (typeof document === 'undefined') return;
+      // create player
```
Comment (ruisaraiva19) [inline packages/react-youtube/src/YouTube.tsx:326]: Instead of wrapping the `createPlayer` logic into a function, I suggest leaving as it was before and add the following here:
```suggestion
    if (this.destroyPlayerPromise) {
      // We need to first await the existing player to be destroyed before
      // we can re-create it.
      this.destroyPlayerPromise.then(this.createPlayer);
      return;
    }
    // create player
```

File: packages/react-youtube/src/YouTube.tsx [hunk 2]
```diff
@@ -300,37 +306,60 @@ class YouTube extends React.Component<YouTubeProps> {
...
   onPlayerPlaybackQualityChange = (event: YouTubeEvent<string>) => this.props.onPlaybackQualityChange?.(event);
 
+  /**
+   * Destroy the YouTube Player using its async API and store the promise so we
+   * can await before re-creating it.
+   */
+  destroyPlayer = () => {
+    if (this.internalPlayer) {
+      this.destroyPlayerPromise = this.internalPlayer.destroy().then(() => (this.destroyPlayerPromise = undefined));
+    }
```
Comment (ruisaraiva19) [inline packages/react-youtube/src/YouTube.tsx:316]:
```suggestion
    if (this.internalPlayer) {
      this.destroyPlayerPromise = this.internalPlayer.destroy().then(() => (this.destroyPlayerPromise = undefined));
      return this.destroyPlayerPromise;
    }
    return Promise.resolve();
```

File: packages/react-youtube/src/YouTube.tsx [hunk 3]
```diff
@@ -300,37 +306,60 @@ class YouTube extends React.Component<YouTubeProps> {
...
     }
   };
 
   /**
    * Shorthand for destroying and then re-creating the YouTube Player
    */
-  resetPlayer = () => this.internalPlayer?.destroy().then(this.createPlayer);
+  resetPlayer = () => {
+    this.destroyPlayer();
+    this.createPlayer();
```
Comment (ruisaraiva19) [inline packages/react-youtube/src/YouTube.tsx:361]: With the suggestion above we can update this to:
```suggestion
    this.destroyPlayer().then(this.createPlayer);
```

**Review by ruisaraiva19 — CHANGES_REQUESTED** [review]
@victoragnez Thanks for the contribution.

Please take a look at my suggestions and let me know if you have any questions.

**Comment by henninghaakonsen** [comment]
Great fix - our team is also having issues with this.

**Review by ruisaraiva19 — APPROVED** [review]
